"""add sm2 fields

Revision ID: 164cc8de0a3a
Revises: 85349950555a
Create Date: 2026-04-27 14:08:49.244714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164cc8de0a3a'
down_revision = '85349950555a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sm2_easiness_factor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sm2_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sm2_repetitions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sm2_next_review', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sm2_last_review', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('sm2_last_review')
        batch_op.drop_column('sm2_next_review')
        batch_op.drop_column('sm2_repetitions')
        batch_op.drop_column('sm2_interval')
        batch_op.drop_column('sm2_easiness_factor')

    # ### end Alembic commands ###
