"""add image path

Revision ID: 85349950555a
Revises: 5bfdb40818ef
Create Date: 2026-04-14 17:17:49.489983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85349950555a'
down_revision = '5bfdb40818ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
